# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title tellme
#'
#' @description Store a number of different compile-time \code{#define} values
#' and returns them in a named character vector.
#'
#' @return A named logical vector.
#' @useDynLib tellme, .registration=TRUE
#' @importFrom Rcpp evalCpp
#' @export
tellme <- function() {
    .Call(`_tellme_tellme`)
}

#' @title versions
#'
#' @description Store the C++ compilation standard and returns it in a named integer vector.
#'
#' @return A named integer vector.
#' @export
versions <- function() {
    .Call(`_tellme_versions`)
}

